### ISSUE TITLE
Issue> following issue appears when I tried to configure openPDC and openHistorian. 

### ISSUE THREAD

**Issue by Khwbas** [GridProtectionAlliance/gsf#103]
please open the link (the issue has been attached)> https://drive.google.com/file/d/1g5TAK7x72o5TUnM8fnj7TWffUxw6cvjo/view?usp=sharing 
Please suggest system requirements for successful configuration
Operational System ?
openPDC ?
GSF ?
Mysql client for dotNe ?
Mysql server ?
I ended up while installing the openPDC and openHistorian https://www.youtube.com/watch?v=N1S-t6dH3LM&t=63s Is this video can be advisable to follow for configuration still?

**Comment by StephenCWills** [comment]
Please attach the image to your issue next time so we can view it here on GitHub.
![OPENPDC](https://user-images.githubusercontent.com/9203145/196201569-7b9d886a-66db-4a28-8a45-fbee4ef5b766.JPG)

This error suggests you should probably run through the Configuration Setup Utility again. The video you linked appears to be using an "existing database as-is" which likely isn't the case if this is your first time setting up the software. Assuming that this is your first time setting things up, and given the information you've provided, I would you to enter the following options to get started.

* I want to set up a new configuration
* Database (suggested)
* MySQL

Also, please also note that the latest version of MySQL Connector/NET that we support is likely to be 6.9.11. Versions later than that have been known to give our software some trouble.

I'm closing this issue since it's more of an openPDC support issue and there's not any issue with the GSF source code. If you have further questions about the setup, I recommend opening a topic on our discussion boards. https://discussions.gridprotectionalliance.org/
