### ISSUE TITLE
[Question] Is it possible to use GSF in Javascript?

### ISSUE THREAD

**Issue by MarcoSulla** [GridProtectionAlliance/gsf#11]
Hello. I read in your documentation that you exposes a Javascript interface. Example: https://www.gridprotectionalliance.org/NightlyBuilds/GridSolutionsFramework/Help/html/T_GSF_PhasorProtocols_IDataFrame.htm

Is it possible to use GSF under a browser client? If so, how can it call functions from the shared library?

**Comment by ritchiecarroll** [comment]
First I am assuming you mean from a web browser, so if this is true then the easiest way would be to use something like SignalR with a .NET backend - that way you could use the code as-is and just serialize needed results to and from Javascript.

Otherwise you might have to do something fancy like using Mono / .NET from Javascript directly:

https://github.com/xmcclure/emscripten-test

That'd be very experimental at this point though...

If you just want to use Javascript as a language for .NET development, try something like this:

https://github.com/paulbartrum/jurassic

Thanks,
Ritchie
