### ISSUE TITLE
Possible GSF.Core.Shared.ArrayExtensions.IndexOfSequence Issue

### ISSUE THREAD

**Issue by ajstadlin** [GridProtectionAlliance/gsf#17]
I'm not sure if this is a problem  or not.  I had to change GSF.Core.Shared.ArrayExtensions.cs Line# 460 from original:
```cs
index = Array.IndexOf(array, sequenceToFind[0], index + 1, length - (index + 1));
```
To:
```cs
index = Array.IndexOf(array, sequenceToFind[0], index + 1, array.Length - (index + 1));
```

The following is a link to a quick console app to test.  Test files 1 and 2 work fine.  Test file 3 breaks with an error like:  
```
An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
Additional information: Count must be positive and count must refer to a location within the string/array/collection.
```

[Link to the test project: Test_ArrayExtensions_IndexOfSequence](https://github.com/ajstadlin/Test_ArrayExtensions_IndexOfSequence)

//AJ

Updated:

I labeled this as a "bug" because it is unexpected behavior that should be fixed.  I am not certain if the fix should be as I described in the code above, or if the fix should be detecting the condition and throwing an exception similar to how other exceptions are handled in the IndexOfSequence routine.  Since the condition throws an unhandled exception anyway, perhaps defining and detecting then throwing a known exception is the way to go since the behavior of the method would not be changed.  Changing the length to array.Length and not throwing an exception might "fix" my special use case, but changes the method's exceptional behavior - possibly affecting or breaking software depending on the exception.

**Comment by ritchiecarroll** [comment]
Certainly what we are trying to avoid here is an `ArgumentOutOfRange` exception for the `count` parameter on the `Array.IndexOf` function so that "_startIndex and count specify a valid section in the array_" - this includes avoiding a negative number :-)

The tricky part here is that the `length` parameter for the `IndexOfSequence` function function "should" specify a _portion_ of the source array to consider - and the subsequent sub-searches should never exceed these bounds, hence `length - (index + 1)`.

However, I'm not 100% sure that your test code evokes the spirit of that notion with this line of code:
```c#
findIndex = GSF.ArrayExtensions.IndexOfSequence(fileBytes, findBytes, findIndex + findBytes.Length);
```
Seems like the `length` parameter here should be more like: `fileBytes.Length - (findIndex - 1)`?

If by changing that, does the program behave as expected? If so, we may want to make the documentation of that function more clear on the meaning of the  `startIndex` and `length` parameters.

Thanks for your continued support and testing AJ!

Ritchie

**Comment by ajstadlin** [comment]
Thank you for your feedback.  This issue is a challenge for me for sure.

I'm calling the function overload:

```cs
public static int IndexOfSequence<T>(this T[] array, T[] sequenceToFind, int startIndex) where T : IComparable<T>
```
From that function's scope, My code can't see the ```length``` in the overload that uses ```length``` as the parameter.  *However, you might notice that your change suggestion looks a lot like the change I have to make to ArrayExtensions.cs line# 460 to get my use case to work.*

I admit I might be miss interpreting the IndexOfSequence function.   In my specific use case (a one-shot utility), I am going to need to call this function on 81559 files.  I figure by the time I work out all of the exceptions, I will have an intimate understanding for how this function works by the time I am done.  It was merely by chance that my "TestDataFile3.bin" file was the First of the 81559 files. 

//AJ

**Comment by ajstadlin** [comment]
If I change ArrayExtensions.cs line# 455 from:
```cs
if (index + x < startIndex + length) 
```
to:
```cs
if ((index + x < startIndex + length) || (length < (index + 1)))
```
The exception is preemptively managed and returns ```index = -1``` when the exception occurs.  This is proving out to be acceptable in my test cases and my use case so far; because the exception only occurs when there are no more occurrences of the sequence being searched for. 

//AJ

**Comment by ritchiecarroll** [comment]
Awesome fix! Want to check that in?

**Comment by StephenCWills** [comment]
Thanks for reporting this, AJ! Ritchie and I had a closer look at this. Looks like we were calculating the count incorrectly when calling Array.IndexOf(). The change I just checked in should fix this issue.

**Comment by ajstadlin** [comment]
Your Fix Works!  I just tested with my use case that calls that function to scan over 81000 files.  100% successful!  

Thank you very much for the Fix!

//AJ

Now I can go home and shovel snow
