### ISSUE TITLE
Concentrated devices not properly updated when device names change

### ISSUE THREAD

**Issue by arkrohne** [GridProtectionAlliance/gsf#3]
If you connect to a C37.118 stream `DEVICE` with devices `RED` and `BLUE`, and then `BLUE` is renamed `GREEN` and you update the config from the wizard, your `DEVICE` will now have all three, with measurements. `BLUE` will not be receiving any data, but will not be automatically removed.

**Comment by StephenCWills** [comment]
Fixed in https://github.com/GridProtectionAlliance/gsf/commit/1d65d39aa0c102a82a7ee95a9555147edeb04a7d. Note that the input wizard has no knowledge of the fact that the upstream device was renamed and will assume that BLUE was deleted and GREEN was added. It will generate a new ID and UniqueID for the device which could have some unexpected side effects in downstream GEP streams. However, this should work fine in most cases.
