### ISSUE TITLE
Configuration Setup Utility does not warn when overwriting sqlite database file

### ISSUE THREAD

**Issue by arkrohne** [GridProtectionAlliance/gsf#4]
If the path to the database already exists, the CSU will not warn the user that it is overwriting the file. 

Discovered when using 'upgrade database' when upgrading from 2.2.9 to 2.2.50, and previous database was already called 'openPDCv22.db'.

**Comment by StephenCWills** [comment]
Fixed in all time-series products.

https://github.com/GridProtectionAlliance/openPDC/commit/33ed5bae498132980062ffa43b7851ab3b989879
https://github.com/GridProtectionAlliance/SIEGate/commit/3aaa30a66728d47923f7fb9cc4d81823f768a7ea
https://github.com/GridProtectionAlliance/openHistorian/commit/f7793ac33e24e5723e7ff65507b291ea35b4c46a
https://github.com/GridProtectionAlliance/substationSBG/commit/755d6bd5d0f40b460ef9bbc43a28c264dfd2b4e6
https://github.com/GridProtectionAlliance/pdqtracker/commit/de877c0b704ece43bbc284775214c8d100b1627f
https://github.com/GridProtectionAlliance/projectalpha/commit/f0c29acc2ce51de7962c4794d23940f6404565ad
https://github.com/GridProtectionAlliance/openECA/commit/9ae16652b4eff76595cdc41fa1b778177affc4ab
